---

rules:
  presents_each: 3
  attempts_limit: 1000
  print: true
  required_fields:
    - 'name'
    - 'email'

people:
  -
    name: "Test 01"
    email: "test01@paul.com"
  -
    name: "Test 02"
    email: "test01@paul.com"
  -
    name: "Test 03"
    email: "test03@paul.com"
  -
    name: "Test 04"
    email: "test04@paul.com"
  -
    name: "Test 05"
    email: "test05@paul.com"

exclusion_sets:
  -
    - "test01@paul.com"
    - "test02@paul.com"
  -
    - "test09@paul.com"
    - "test01@paul.com"
    - "test03@paul.com"
  -
    - "test07@paul.com"
    - "test04@paul.com"
  -
    - "test06@paul.com"
    - "test08@paul.com"
  -
    - "test06@paul.com"
    - "test07@paul.com"